<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keluar</name>
   <tag></tag>
   <elementGuidId>9b42ee9c-782f-4625-94da-e603784bfc27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Keluar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.user-avatar > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c27ccb9b-d590-41f6-a6ba-e82dd9e038e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berrybenka.com/logout</value>
      <webElementGuid>7490c276-ae18-4642-a6e3-072ee2323424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>951d829d-bc42-4439-9a41-984fe0587375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;user-wrapper clearfix&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;user-wrap&quot;]/div[@class=&quot;user-menu left&quot;]/div[@class=&quot;user-avatar&quot;]/a[1]</value>
      <webElementGuid>163f3045-ad14-432b-8bac-e678ab2d98f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>45bb6c20-9b25-4c56-8526-21ba87ba1a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luthfita Tiananda Yasin'])[2]/following::a[1]</value>
      <webElementGuid>1e076805-ec09-4a6a-a798-253699097f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>8e99e810-a94a-43c9-af08-0d81a2edb97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halaman Akun'])[1]/preceding::a[1]</value>
      <webElementGuid>3fdfac50-38fa-4700-853b-7026e40b9beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/preceding::a[2]</value>
      <webElementGuid>d437200d-79b0-46bd-b43f-c86d38fc10c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>302e41b5-ed39-42cc-b0a4-c72bdbcafd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://berrybenka.com/logout')]</value>
      <webElementGuid>478eb437-2508-43a1-8b8f-8a111071915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>1532b793-2aa0-4b7b-bca9-25ccb0aec46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berrybenka.com/logout' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>2c17e35f-a463-48ca-8405-6f9d1106f6d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
